### ISSUE TITLE
Assembly polarity in accordance IPC-7351C

### ISSUE THREAD

**Issue by eldarkg** [KiCad/Oscillators.pretty#6]
Should be
![Polarity](https://user-images.githubusercontent.com/5782069/26841971-e47e2758-4af3-11e7-901c-5605e84be23e.png)

**Comment by poeschlr** [comment]
Have you seen the [kicad library convention](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)?
Also have a look at the [FAQ](https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions) especially the fabrication layer section might be of interest.
Remember not all footprints are KLC compliment.

There is also a [discussion for the next version](https://github.com/KiCad/kicad-library/issues/1143) of the library convention. If the convention contradicts the standard somehow let us know there. 
Please highlight the part of the convention that contradicts this picture of yours. (I think what you posted is only a small subset of pin 1 markers that are allowed in the standard.)

**Comment by eldarkg** [comment]
@poeschlr
Affected footprints:
Oscillator_DIP-*
Oscillator_SMD_*

**Comment by eldarkg** [comment]
@poeschlr [Examples](https://github.com/KiCad/Crystals.pretty/issues/23#issuecomment-307153875)

**Comment by SchrodingersGat** [comment]
@eldarkg I am marking this issue as closed so that I can archive this repository. The new footprint repository is available at https://github.com/kicad/kicad-footpritns

If you feel that this issue remains unresolved, please re-open a new issue at the new repo :)

Thanks!
