### ISSUE TITLE
Help with Oscillator footprint

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/Oscillators.pretty#7]
Hi guys
any good idea how to make this footprint properly and keep the small size?
I guess the 0.2mm clearance is kinda tricky for these small components
![asco](https://user-images.githubusercontent.com/5279723/32052244-e5d682ca-ba57-11e7-931a-f45352b497a9.png)

![asco_1_6x1_2mm](https://user-images.githubusercontent.com/5279723/32052264-f266985e-ba57-11e7-9f4c-5121e52a5ca0.png)

**Comment by SchrodingersGat** [comment]
You could always have two versions, one with silkscreen and one without? This is the practice for e.g. small resistors / capacitors.

**Comment by Shackmeister** [comment]
How would pin 1 be shown?
On the version in my own library I remade it with 0.1mm clearance and that seems to work fine

**Comment by SchrodingersGat** [comment]
You can always specify an explicit (smaller) clearance for the pads. I'm going to close this issue as we are marking the v4 repos as archived. Please direct your attention to the new repo at https://github.com/kicad/kicad-footprints

Thanks!
